[tool.poetry]
name = "technicalutils"
version = "0.1.0"
description = ""
authors = ["edayot <pro.e.dayot@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
beet = "^0.105.0"
mecha = "^0.94.0"
weld-deps = "^0.6.0"
frozendict = "^2.4.2"

[tool.poetry.dev-dependencies]
python-semantic-release = "^8.7.0"





[tool.semantic_release]
major_on_zero = false
build_command = '''
    beet -s data_pack.zipped=true \
         -s resource_pack.zipped=true \
         -s meta.weld_deps.enabled=true && \
    beet -s data_pack.zipped=true \
         -s resource_pack.zipped=true \
         -s meta.weld_deps.enabled=false \
         -s data_pack.name="{{ project_id }}_{{ project_version }}_dp" \
         -s resource_pack.name="{{ project_id }}_{{ project_version }}_rp"
'''
dist_path = "build"
version_toml = ["pyproject.toml:tool.poetry.version"]
version_source = "commit"

remove_dist = false
tag_format = "v{version}"

[tool.semantic_release.publish]
dist_glob_patterns = ["build/*.zip"]
upload_to_vcs_release = true



[tool.beet]
output = "build"

pipeline = [
    "technicalutils",
    "mecha",
]
require=[
    "weld_deps",
    "mecha.contrib.relative_location",
    "mecha.contrib.nested_location",
]

[tool.beet.data_pack]
name = "{{ project_id }}_{{ project_version }}_dp_bundled"
load = "."

[tool.beet.resource_pack]
name = "{{ project_id }}_{{ project_version }}_rp_bundled"
load = "."

[tool.beet.meta]
mc_supports = ["1.20.5"]

[tool.beet.meta.mecha]
multiline = true


[tool.beet.meta.weld_deps]
enable_weld_merging=true
clean_load_tag=true
include_prerelease=false


[[tool.beet.meta.weld_deps.deps]]
id = "itemio"
match = ">=0.14.1"
source = "smithed"

[[tool.beet.meta.weld_deps.deps]]
id = "energy"
match = ">=1.7.0"
source = "smithed"


[[tool.beet.meta.weld_deps.deps]]
id = "nbtsmelting"
match = ">=1.7.0"
source = "smithed"


[[tool.beet.meta.weld_deps.deps]]
id = "fluid_crafting"
match = ">=1.5.0"
source = "smithed"
